
const years = document.querySelector("select#year");
const manufacturer = document.querySelector("select#manufacturer");
const model = document.querySelector("select#model");
const type = document.querySelector("select#type");

const manufacturersOption = document.createElement("option");



years.addEventListener(
  "change",
  (event = () => {
    console.log("click");
    manufacturer.insertAdjacentHTML("beforeend", manufacturerId);;
  })
);



model.addEventListener(
  "change",
  (event = () => {
    console.log("click");
    type.innerHTML = "<option>3.5L SL</option>";
  })
);


const manufacture = [
  { id: 3854, matchcode: "ABARTH" },
  { id: 609, matchcode: "AC" },
  { id: 1505, matchcode: "ACURA" },
  { id: 4593, matchcode: "ACURA GAC" },
  { id: 128, matchcode: "AGRALE" },
  { id: 1480, matchcode: "AIXAM" },
  { id: 2, matchcode: "ALFA" },
  { id: 4414, matchcode: "ALPHEON" },
  { id: 866, matchcode: "ALPI" },
  { id: 810, matchcode: "ALPIN" },
  { id: 4730, matchcode: "ALVIS" },
  { id: 2775, matchcode: "AM GENERAL" },
  { id: 2246, matchcode: "AMC" },
  { id: 3526, matchcode: "ANADOL" },
  { id: 2847, matchcode: "ANCHI" },
  { id: 3971, matchcode: "ANDORIA" },
  { id: 2848, matchcode: "ANFINI" },
  { id: 2526, matchcode: "ARMSTRONGS" },
  { id: 1360, matchcode: "ARO" },
  { id: 3495, matchcode: "ARTEGA" },
  { id: 2241, matchcode: "ASHOK LEYL" },
  { id: 879, matchcode: "ASIAM" },
  { id: 2242, matchcode: "ASKAM" },
  { id: 881, matchcode: "ASTON" },
  { id: 2706, matchcode: "ASUNA" },
  { id: 5, matchcode: "AUDI" },
  { id: 2858, matchcode: "AUDI FAW" },
  { id: 6, matchcode: "AUSTI" },
  { id: 1538, matchcode: "AUSTIN-HEA" },
  { id: 4600, matchcode: "AUTOAR" },
  { id: 799, matchcode: "AUTOB" },
  { id: 3, matchcode: "AUTOU" },
  { id: 3842, matchcode: "AUTOZAM" },
  { id: 2845, matchcode: "AUVERLAND" },
  { id: 2707, matchcode: "AVANTI" },
  { id: 132, matchcode: "AVIA" },
  { id: 4626, matchcode: "BAHMAN" },
  { id: 3773, matchcode: "BAIC" },
  { id: 4418, matchcode: "BAIC BJEV" },
  { id: 4266, matchcode: "BAIC WW" },
  { id: 4036, matchcode: "BAICHUANSU" },
  { id: 2849, matchcode: "BAJAJTEMPO" },
  { id: 3764, matchcode: "BAOJUN" },
  { id: 2906, matchcode: "BAOLONG" },
  { id: 134, matchcode: "BARKA" },
  { id: 3071, matchcode: "BAW" },
  { id: 3142, matchcode: "BBDC" },
  { id: 10, matchcode: "BEDFO" },
  { id: 815, matchcode: "BENT" },
  { id: 1485, matchcode: "BERT" },
  { id: 3762, matchcode: "BESTURN" },
  { id: 4645, matchcode: "BIO AUTO" },
  { id: 4637, matchcode: "BISU" },
  { id: 1486, matchcode: "BITTER" },
  { id: 4712, matchcode: "BLUECAR" },
  { id: 16, matchcode: "BMW" },
  { id: 3124, matchcode: "BMW BRIL" },
  { id: 4439, matchcode: "BOGDAN" },
  { id: 1537, matchcode: "BOND" },
  { id: 136, matchcode: "BORGW" },
  { id: 4161, matchcode: "BRABUS" },
  { id: 2708, matchcode: "BRICKLIN" },
  { id: 3076, matchcode: "BRILLIANCE" },
  { id: 1487, matchcode: "BRIST" },
  { id: 4162, matchcode: "BUFORI" },
  { id: 788, matchcode: "BUGAT" },
  { id: 816, matchcode: "BUICK" },
  { id: 3136, matchcode: "BUICK SGM" },
  { id: 3122, matchcode: "BYD" },
  { id: 819, matchcode: "CADIL" },
  { id: 3528, matchcode: "CADILL SGM" },
  { id: 1488, matchcode: "CALLA" },
  { id: 3770, matchcode: "CAM" },
  { id: 1489, matchcode: "CARBO" },
  { id: 2915, matchcode: "CASALINI" },
  { id: 1490, matchcode: "CATE" },
  { id: 3678, matchcode: "CHAMONIX" },
  { id: 4609, matchcode: "CHANA" },
  { id: 2852, matchcode: "CHANGAN" },
  { id: 2889, matchcode: "CHANGFENG" },
  { id: 2853, matchcode: "CHANGHE" },
  { id: 1491, matchcode: "CHECK" },
  { id: 2887, matchcode: "CHERY" },
  { id: 138, matchcode: "CHEVR" },
  { id: 3527, matchcode: "CHEVR  SGM" },
  { id: 3651, matchcode: "CHEVR SGMW" },
  { id: 20, matchcode: "CHRYS" },
  { id: 3646, matchcode: "CHRYS BBDC" },
  { id: 4177, matchcode: "CHTC AUTO" },
  { id: 21, matchcode: "CITRO" },
  { id: 2891, matchcode: "CITROEN DF" },
  { id: 3772, matchcode: "CMC" },
  { id: 3719, matchcode: "CODA" },
  { id: 4214, matchcode: "COWIN" },
  { id: 139, matchcode: "DACIA" },
  { id: 2901, matchcode: "DADI" },
  { id: 185, matchcode: "DAEWOO" },
  { id: 24, matchcode: "DAF" },
  { id: 25, matchcode: "DAIHA" },
  { id: 3274, matchcode: "DAIHAT FAW" },
  { id: 26, matchcode: "DAIML" },
  { id: 1493, matchcode: "DALLA" },
  { id: 807, matchcode: "DATSUN" },
  { id: 4267, matchcode: "DAYUN" },
  { id: 4717, matchcode: "DE LA CHAP" },
  { id: 1494, matchcode: "DELOR" },
  { id: 4089, matchcode: "DENZA" },
  { id: 3069, matchcode: "DERWAYS" },
  { id: 1495, matchcode: "DETOM" },
  { id: 4264, matchcode: "DF FENGDU" },
  { id: 2854, matchcode: "DFAC" },
  { id: 4269, matchcode: "DFSK" },
  { id: 3152, matchcode: "DFXIAOKANG" },
  { id: 29, matchcode: "DODGE" },
  { id: 2855, matchcode: "DONGNAN" },
  { id: 4658, matchcode: "DONKERVOOR" },
  { id: 3497, matchcode: "DR" },
  { id: 4468, matchcode: "DS" },
  { id: 3999, matchcode: "DS(CAPSA)" },
  { id: 824, matchcode: "EAGLE" },
  { id: 142, matchcode: "EBRO" },
  { id: 3652, matchcode: "EFFA" },
  { id: 3618, matchcode: "EFFEDI" },
  { id: 3332, matchcode: "EMGRAND" },
  { id: 4541, matchcode: "ENGESA" },
  { id: 3704, matchcode: "ENGLON" },
  { id: 2857, matchcode: "EUNOS" },
  { id: 3267, matchcode: "EUROPESTAR" },
  { id: 2709, matchcode: "EXCALIBUR" },
  { id: 3610, matchcode: "FAW" },
  { id: 2909, matchcode: "FAW JILIN" },
  { id: 2890, matchcode: "FAW TJ" },
  { id: 2862, matchcode: "FENGSHEN" },
  { id: 2863, matchcode: "FENGXING" },
  { id: 700, matchcode: "FERRA" },
  { id: 35, matchcode: "FIAT" },
  { id: 3131, matchcode: "FIAT NANJI" },
  { id: 3761, matchcode: "FIAT_GAC" },
  { id: 3738, matchcode: "FISKER" },
  { id: 3771, matchcode: "FODAY" },
  { id: 2850, matchcode: "FORCE" },
  { id: 36, matchcode: "FORD" },
  { id: 2864, matchcode: "FORD A / O" },
  { id: 3125, matchcode: "FORD CHANG" },
  { id: 3656, matchcode: "FORD JMC" },
  { id: 776, matchcode: "FORD USA" },
  { id: 1496, matchcode: "FORDA" },
  { id: 808, matchcode: "FORDOTOSAN" },
  { id: 2865, matchcode: "FORTA" },
  { id: 2867, matchcode: "FOTON" },
  { id: 3297, matchcode: "FPV" },
  { id: 4257, matchcode: "FQT MOTOR" },
  { id: 147, matchcode: "FREIGTLINE" },
  { id: 775, matchcode: "FSO" },
  { id: 2875, matchcode: "FUQI" },
  { id: 3196, matchcode: "GAC" },
  { id: 3997, matchcode: "GACGONOW" },
  { id: 148, matchcode: "GAZ" },
  { id: 2590, matchcode: "GEELY" },
  { id: 4473, matchcode: "GENESIS" },
  { id: 831, matchcode: "GEO" },
  { id: 4657, matchcode: "GERMAN E-C" },
  { id: 1498, matchcode: "GINET" },
  { id: 812, matchcode: "GLAS" },
  { id: 3697, matchcode: "GLEAGLE" },
  { id: 39, matchcode: "GMC" },
  { id: 3158, matchcode: "GOLDEN DRA" },
  { id: 2902, matchcode: "GONOW" },
  { id: 2903, matchcode: "GREAT WALL" },
  { id: 2926, matchcode: "GRECAV" },
  { id: 4640, matchcode: "GROZ" },
  { id: 2249, matchcode: "GURGEL" },
  { id: 2866, matchcode: "HAFEI" },
  { id: 3036, matchcode: "HAIMA(FAW)" },
  { id: 3913, matchcode: "HAIMA(ZZ)" },
  { id: 4610, matchcode: "HANTENG" },
  { id: 3968, matchcode: "HAVAL" },
  { id: 3562, matchcode: "HAWTAI" },
  { id: 4450, matchcode: "HEIBAO" },
  { id: 4268, matchcode: "HENGTONG" },
  { id: 4176, matchcode: "HIGER" },
  { id: 2794, matchcode: "HILLMAN" },
  { id: 1499, matchcode: "HINDU" },
  { id: 1500, matchcode: "HOBBY" },
  { id: 801, matchcode: "HOLDE" },
  { id: 45, matchcode: "HONDA" },
  { id: 3126, matchcode: "HONDA DF" },
  { id: 3129, matchcode: "HONDA GAC" },
  { id: 2871, matchcode: "HONGQI" },
  { id: 3276, matchcode: "HSV" },
  { id: 2872, matchcode: "HUALI" },
  { id: 4258, matchcode: "HUANGHAI" },
  { id: 4255, matchcode: "HUASONG" },
  { id: 4320, matchcode: "HUAYANG" },
  { id: 4729, matchcode: "HUMBER" },
  { id: 1506, matchcode: "HUMME" },
  { id: 183, matchcode: "HYUNDAI" },
  { id: 3123, matchcode: "HYUNDAI BJ" },
  { id: 3128, matchcode: "HYUNDAI HU" },
  { id: 3507, matchcode: "ICML" },
  { id: 4536, matchcode: "IES" },
  { id: 2798, matchcode: "IF" },
  { id: 4535, matchcode: "IKA" },
  { id: 3084, matchcode: "IKCO" },
  { id: 1507, matchcode: "INDIGO" },
  { id: 1526, matchcode: "INFIN" },
  { id: 4211, matchcode: "INFINITIDF" },
  { id: 52, matchcode: "INNOC" },
  { id: 3677, matchcode: "INOKOM" },
  { id: 2460, matchcode: "INTERNATIO" },
  { id: 1508, matchcode: "IRMSCHER" },
  { id: 1509, matchcode: "ISDER" },
  { id: 1510, matchcode: "ISH" },
  { id: 54, matchcode: "ISUZU" },
  { id: 4393, matchcode: "ISUZU JIAN" },
  { id: 55, matchcode: "IVECO" },
  { id: 4683, matchcode: "IZH" },
  { id: 2873, matchcode: "JAC" },
  { id: 56, matchcode: "JAGUA" },
  { id: 4614, matchcode: "JAGUAR CN" },
  { id: 882, matchcode: "JEEP" },
  { id: 2851, matchcode: "JEEP BJC" },
  { id: 4454, matchcode: "JEEP GAC" },
  { id: 1511, matchcode: "JENSE" },
  { id: 2908, matchcode: "JIANGNAN" },
  { id: 2888, matchcode: "JINBEI BRI" },
  { id: 4179, matchcode: "JINCHENG" },
  { id: 3040, matchcode: "JMC" },
  { id: 3993, matchcode: "JONWAY" },
  { id: 4180, matchcode: "JOYLONG" },
  { id: 4265, matchcode: "KAMA" },
  { id: 4390, matchcode: "KANDI" },
  { id: 3286, matchcode: "KARRY" },
  { id: 4181, matchcode: "KAWEI AUTO" },
  { id: 184, matchcode: "KIA" },
  { id: 3127, matchcode: "KIA DYK" },
  { id: 3805, matchcode: "KING LONG" },
  { id: 4163, matchcode: "KOENIGSEGG" },
  { id: 2760, matchcode: "KTM" },
  { id: 63, matchcode: "LADA" },
  { id: 2710, matchcode: "LAFORZA" },
  { id: 701, matchcode: "LAMBO" },
  { id: 64, matchcode: "LANCIA" },
  { id: 1820, matchcode: "LANDROVER" },
  { id: 2589, matchcode: "LANDWIND" },
  { id: 1380, matchcode: "LDV" },
  { id: 842, matchcode: "LEXUS" },
  { id: 2407, matchcode: "LEYLAND-IN" },
  { id: 3086, matchcode: "LIFAN" },
  { id: 1513, matchcode: "LIGIER" },
  { id: 1200, matchcode: "LINCO" },
  { id: 4187, matchcode: "LLOYD" },
  { id: 3679, matchcode: "LOBINI" },
  { id: 802, matchcode: "LOTUS" },
  { id: 3661, matchcode: "LOTUS_YOUN" },
  { id: 4282, matchcode: "LR CHERY" },
  { id: 3047, matchcode: "LTI" },
  { id: 1515, matchcode: "LUAZ" },
  { id: 3742, matchcode: "LUXGEN" },
  { id: 1280, matchcode: "MAHINDRA" },
  { id: 3554, matchcode: "MAHINDRA R" },
  { id: 69, matchcode: "MAN" },
  { id: 2905, matchcode: "MAPLE SMA" },
  { id: 1516, matchcode: "MARCOS" },
  { id: 908, matchcode: "MARUT" },
  { id: 3549, matchcode: "MARUTSU" },
  { id: 771, matchcode: "MASER" },
  { id: 3794, matchcode: "MASTRETTA" },
  { id: 3300, matchcode: "MAXUS" },
  { id: 2164, matchcode: "MAYB" },
  { id: 72, matchcode: "MAZDA" },
  { id: 3532, matchcode: "MAZDA CHAN" },
  { id: 3138, matchcode: "MAZDA FAW" },
  { id: 2868, matchcode: "MAZDA HAIN" },
  { id: 1518, matchcode: "MCLAREN" },
  { id: 845, matchcode: "MEGA" },
  { id: 74, matchcode: "MERCE" },
  { id: 3645, matchcode: "MERCE BBDC" },
  { id: 3522, matchcode: "MERCE FJDA" },
  { id: 161, matchcode: "MERCURY" },
  { id: 2711, matchcode: "MERKUR" },
  { id: 1520, matchcode: "METROCAB" },
  { id: 75, matchcode: "MG" },
  { id: 3133, matchcode: "MG NANJING" },
  { id: 3838, matchcode: "MG SAIC" },
  { id: 3961, matchcode: "MIA" },
  { id: 4219, matchcode: "MICROCAR" },
  { id: 1521, matchcode: "MIDDL" },
  { id: 1522, matchcode: "MINELLI" },
  { id: 1523, matchcode: "MINI" },
  { id: 3648, matchcode: "MITSU BBDC" },
  { id: 3650, matchcode: "MITSU BJC" },
  { id: 3658, matchcode: "MITSUB SOU" },
  { id: 77, matchcode: "MITSUBISHI" },
  { id: 2904, matchcode: "MITSUOKA" },
  { id: 3837, matchcode: "MITSU_GAC" },
  { id: 4501, matchcode: "MOBILITY V" },
  { id: 803, matchcode: "MORGA" },
  { id: 78, matchcode: "MORRI" },
  { id: 813, matchcode: "MOSKV" },
  { id: 4605, matchcode: "MULTIX" },
  { id: 3132, matchcode: "NAVECO" },
  { id: 3070, matchcode: "NAZA" },
  { id: 4277, matchcode: "NDY" },
  { id: 80, matchcode: "NISSA" },
  { id: 3141, matchcode: "NISSAN DF" },
  { id: 2910, matchcode: "NISSAN ZZ" },
  { id: 3625, matchcode: "NOBLE" },
  { id: 81, matchcode: "NSU" },
  { id: 1141, matchcode: "OLDS" },
  { id: 1527, matchcode: "OLTCI" },
  { id: 84, matchcode: "OPEL" },
  { id: 1529, matchcode: "OSCA" },
  { id: 2806, matchcode: "PACKARD" },
  { id: 4164, matchcode: "PAGANI" },
  { id: 1530, matchcode: "PANOZ" },
  { id: 1531, matchcode: "PANTH" },
  { id: 1532, matchcode: "PAYKA" },
  { id: 1533, matchcode: "PERODUA" },
  { id: 88, matchcode: "PEUGE" },
  { id: 3531, matchcode: "PEUGEOT DF" },
  { id: 4659, matchcode: "PGO" },
  { id: 181, matchcode: "PIAGGIO" },
  { id: 3046, matchcode: "PININFARIN" },
  { id: 850, matchcode: "PLYMOUTH" },
  { id: 3154, matchcode: "POLARSUN" },
  { id: 774, matchcode: "PONTI" },
  { id: 92, matchcode: "PORSC" },
  { id: 851, matchcode: "PREMI" },
  { id: 778, matchcode: "PROTO" },
  { id: 1580, matchcode: "PUCH" },
  { id: 880, matchcode: "PUMA" },
  { id: 3740, matchcode: "PYEONGHWA" },
  { id: 3139, matchcode: "QINGLING" },
  { id: 3839, matchcode: "QOROS" },
  { id: 2712, matchcode: "QVALE" },
  { id: 3689, matchcode: "RAM" },
  { id: 1534, matchcode: "RANGER" },
  { id: 4660, matchcode: "RAVON" },
  { id: 1536, matchcode: "RAYTO" },
  { id: 773, matchcode: "RELIANT" },
  { id: 3284, matchcode: "RELY" },
  { id: 93, matchcode: "RENAU" },
  { id: 694, matchcode: "RENAULT" },
  { id: 4538, matchcode: "RENAULT DF" },
  { id: 3555, matchcode: "REVA" },
  { id: 3285, matchcode: "RIICH" },
  { id: 1539, matchcode: "RILEY" },
  { id: 3202, matchcode: "ROEWE SAIC" },
  { id: 705, matchcode: "ROLLS" },
  { id: 4708, matchcode: "ROMANITAL" },
  { id: 95, matchcode: "ROVER" },
  { id: 4152, matchcode: "RUF" },
  { id: 99, matchcode: "SAAB" },
  { id: 3155, matchcode: "SAIC HUIZH" },
  { id: 4592, matchcode: "SAIPA" },
  { id: 2713, matchcode: "SALEEN" },
  { id: 4260, matchcode: "SAMSUNG" },
  { id: 1544, matchcode: "SAN" },
  { id: 171, matchcode: "SANTANA" },
  { id: 1545, matchcode: "SAO" },
  { id: 1497, matchcode: "SATUR" },
  { id: 2714, matchcode: "SCION" },
  { id: 104, matchcode: "SEAT" },
  { id: 1547, matchcode: "SHELB" },
  { id: 4661, matchcode: "SHINERAY A" },
  { id: 3156, matchcode: "SHUANGHUAN" },
  { id: 3273, matchcode: "SHUGUANG" },
  { id: 4537, matchcode: "SIAM" },
  { id: 4731, matchcode: "SINGER" },
  { id: 1548, matchcode: "SIPAN" },
  { id: 106, matchcode: "SKODA" },
  { id: 3530, matchcode: "SKODA SVW" },
  { id: 1138, matchcode: "SMART" },
  { id: 3153, matchcode: "SOYAT" },
  { id: 1549, matchcode: "SPECTRE" },
  { id: 4627, matchcode: "SPERANZA" },
  { id: 2755, matchcode: "SPYKER" },
  { id: 4010, matchcode: "SRT" },
  { id: 175, matchcode: "SSANG" },
  { id: 1550, matchcode: "STAND" },
  { id: 2810, matchcode: "STANGUELLI" },
  { id: 1540, matchcode: "STERL" },
  { id: 176, matchcode: "STEYR" },
  { id: 4015, matchcode: "STREETSCOO" },
  { id: 2715, matchcode: "STUDEBAKER" },
  { id: 107, matchcode: "SUBAR" },
  { id: 2716, matchcode: "SUNBEAM" },
  { id: 109, matchcode: "SUZUK" },
  { id: 3143, matchcode: "SUZUKI CHA" },
  { id: 3199, matchcode: "SUZUKI CHH" },
  { id: 4611, matchcode: "SWM" },
  { id: 3680, matchcode: "TAC" },
  { id: 4292, matchcode: "TAGAZ" },
  { id: 110, matchcode: "TALBO" },
  { id: 178, matchcode: "TATA" },
  { id: 3443, matchcode: "TAZZARI" },
  { id: 3328, matchcode: "TESLA M." },
  { id: 4644, matchcode: "THAIRUNG" },
  { id: 3514, matchcode: "THINK" },
  { id: 3048, matchcode: "TIANMA" },
  { id: 3157, matchcode: "TIANQI M A" },
  { id: 1551, matchcode: "TOFAS" },
  { id: 4449, matchcode: "TONGBAO" },
  { id: 4448, matchcode: "TONGJIAFU" },
  { id: 2913, matchcode: "TONGTIAN" },
  { id: 111, matchcode: "TOYOT" },
  { id: 3137, matchcode: "TOYOTA FAW" },
  { id: 3130, matchcode: "TOYOTA GAC" },
  { id: 187, matchcode: "TRABA" },
  { id: 112, matchcode: "TRIUM" },
  { id: 3681, matchcode: "TROLLER" },
  { id: 861, matchcode: "TVR" },
  { id: 1553, matchcode: "UAZ" },
  { id: 3159, matchcode: "UFO" },
  { id: 1554, matchcode: "UMM" },
  { id: 4310, matchcode: "VAM" },
  { id: 117, matchcode: "VAUXH" },
  { id: 1555, matchcode: "VECTO" },
  { id: 4646, matchcode: "VEM" },
  { id: 4636, matchcode: "VENIRAUTO" },
  { id: 1556, matchcode: "VENTU" },
  { id: 3799, matchcode: "VENUCIA" },
  { id: 4256, matchcode: "VICTORYAUT" },
  { id: 4647, matchcode: "VM 77" },
  { id: 120, matchcode: "VOLVO" },
  { id: 4167, matchcode: "VOLVO ASIA" },
  { id: 3533, matchcode: "VOLVO CHAN" },
  { id: 3752, matchcode: "VPG" },
  { id: 121, matchcode: "VW" },
  { id: 2859, matchcode: "VW FAW" },
  { id: 3035, matchcode: "VW SVW" },
  { id: 3191, matchcode: "WANFENG" },
  { id: 186, matchcode: "WARTB" },
  { id: 907, matchcode: "WESTFIELD" },
  { id: 1558, matchcode: "WIESMANN" },
  { id: 1541, matchcode: "WOLSE" },
  { id: 3696, matchcode: "WORKHORSE" },
  { id: 2874, matchcode: "WULING" },
  { id: 3140, matchcode: "WULINGSGMW" },
  { id: 3186, matchcode: "XINKAI" },
  { id: 4002, matchcode: "YEMA AUTO" },
  { id: 4169, matchcode: "YINGZHI" },
  { id: 3193, matchcode: "YUEJIN" },
  { id: 2816, matchcode: "YUGO" },
  { id: 1559, matchcode: "YULON" },
  { id: 3194, matchcode: "YUNQUE" },
  { id: 124, matchcode: "ZASTA" },
  { id: 1139, matchcode: "ZAZ" },
  { id: 4599, matchcode: "ZD" },
  { id: 4604, matchcode: "ZENOSCARS" },
  { id: 2736, matchcode: "ZHONGHUA" },
  { id: 2911, matchcode: "ZHONGXING" },
  { id: 2932, matchcode: "ZIL" },
  { id: 4033, matchcode: "ZINORO" },
  { id: 3160, matchcode: "ZOTYE" },
  { id: 678, matchcode: "ZUEND" },
];

const manufacturerId = listManuf(manufacture);


manufacturer.addEventListener(
  "change",
  (event = () => {
    console.log("click");
      })
);




function listManuf(manufacture) {
  return manufacture
    .map(
      ({ id, matchcode }) =>
        `<option>${matchcode}
      </optiom>`
    )
    .join("");
}